=== apache/solr-site/plugins/vex/schema/vex-input.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "title": "CycloneDX Software Bill of Materials Standard",
  "items": {
    "type": "object",
    "required": [
      "ids",
      "versions",
      "jars",
      "analysis"
    ],
    "additionalProperties": false,
    "properties": {
      "ids": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "jars": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "versions": {
        "type": "string"
      },
      "analysis": {
        "$ref": "file:bom-1.4.schema.json#/definitions/vulnerability/properties/analysis"
      }
    }
  }
}

=== apache/solr-site/vex-input/CVE-2023-51074.json
{
  "ids": [
    "CVE-2023-51074",
    "GHSA-pfh2-hfmq-phg5"
  ],
  "versions": "all",
  "jars": [
    "json-path-2.8.0.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "The only places we use json-path is for querying (via Calcite) and for transforming/indexing custom JSON. Since the advisory describes a problem that is limited to the current thread, and users that are allowed to query/transform/index are already trusted to cause load to some extent, this advisory does not appear to have impact on the way json-path is used in Solr."
  }
}

=== apache/solr-site/vex-input/CVE-2016-6809.json
{
  "ids": [
    "CVE-2016-6809",
    "CVE-2018-1335",
    "CVE-2018-1338",
    "CVE-2018-1339"
  ],
  "versions": "5.5.5, 6.2.0-today",
  "jars": [
    "vorbis-java-tika-0.8.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "See https://github.com/Gagravarr/VorbisJava/issues/30; reported CVEs are not related to OggVorbis at all."
  }
}

=== apache/solr-site/vex-input/CVE-2017-15095.json
{
  "ids": [
    "CVE-2017-15095",
    "CVE-2017-17485",
    "CVE-2017-7525",
    "CVE-2018-5968",
    "CVE-2018-7489",
    "CVE-2019-12086",
    "CVE-2019-12384",
    "CVE-2018-12814",
    "CVE-2019-14379",
    "CVE-2019-14439",
    "CVE-2020-35490",
    "CVE-2020-35491",
    "CVE-2021-20190",
    "CVE-2019-14540",
    "CVE-2019-16335"
  ],
  "versions": "4.7.0-today",
  "jars": [
    "jackson-databind-*.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "These CVEs, and most of the known jackson-databind CVEs since 2017, are all related to problematic 'gadgets' that could be exploited during deserialization of untrusted data. The Jackson developers described 4 conditions that must be met in order for a problematic gadget to be exploited. See https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062. Solr's use of jackson-databind does not meet 1 of the 4 conditions described which makes these CVEs unexploitable. The specific condition that Solr does not meet is the 3rd one: 'Enable polymorphic type handling' Solr does not include any polymorphic type handling, and Solr does not configure jackson-databind de/serialization to expect or include class names in serialized JSON. Two CVEs, 2019-14540 & 2019-16335, are related to HikariConfig and HikariDataSource classes, neither of which are used in Solr's code base."
  }
}

=== apache/solr-site/vex-input/CVE-2014-7940.json
{
  "ids": [
    "CVE-2014-7940",
    "CVE-2016-6293",
    "CVE-2016-7415",
    "CVE-2017-14952",
    "CVE-2017-17484",
    "CVE-2017-7867",
    "CVE-2017-7868"
  ],
  "versions": "7.3.1",
  "jars": [
    "lucene-analyzers-icu-7.3.1.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "All of these issues apply to the C++ release of ICU and not ICU4J, which is what Lucene uses."
  }
}

=== apache/solr-site/vex-input/CVE-2018-1471.json
{
  "ids": [
    "CVE-2018-1471"
  ],
  "versions": "5.4.0-7.7.2, 8.0-8.3",
  "jars": [
    "simple-xml-2.7.1.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Dependency of Carrot2 and used during compilation, not at runtime (see SOLR-769. This .jar was replaced in Solr 8.3 and backported to 7.7.3 (see SOLR-13779)."
  }
}

=== apache/solr-site/vex-input/CVE-2021-33813.json
{
  "ids": [
    "CVE-2021-33813"
  ],
  "versions": "to present",
  "jars": [
    "jdom-*.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "JDOM is only used in Solr Cell, which should not be used in production which makes the vulnerability unexploitable. It is a dependency of Apache Tika, which has analyzed the issue and determined the vulnerability is limited to two libraries not commonly used in search applications, see TIKA-3488 for details. Since Tika should be used outside of Solr, use a version of Tika which updates the affected libraries if concerned about exposure to this issue."
  }
}

=== apache/solr-site/vex-input/CVE-2022-42889.json
{
  "ids": [
    "CVE-2022-42889"
  ],
  "versions": "< 9.1",
  "jars": [
    "commons-text-1.9.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Solr uses commons-text directly (StringEscapeUtils.escapeEcmaScript) in LoadAdminUiServlet that is not vulnerable. Solr also has a \"hadoop-auth\" module that uses Apache Hadoop which uses commons-text through commons-configuration2. For Solr, the concern is limited to loading Hadoop configuration files that would only ever be provided by trusted administrators, not externally (untrusted)."
  }
}

=== apache/solr-site/vex-input/CVE-2014-0114.json
{
  "ids": [
    "CVE-2014-0114"
  ],
  "versions": "4.9.0-7.5.0",
  "jars": [
    "commons-beanutils-1.8.3.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "This is only used at compile time and it cannot be used to attack Solr. Since it is generally unnecessary, the dependency has been removed as of 7.5.0. See SOLR-12617."
  }
}
