=== apache/solr-site/plugins/vex/schema/vex-input.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "title": "CycloneDX Software Bill of Materials Standard",
  "items": {
    "type": "object",
    "required": [
      "ids",
      "versions",
      "jars",
      "analysis"
    ],
    "additionalProperties": false,
    "properties": {
      "ids": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "jars": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "versions": {
        "type": "string"
      },
      "analysis": {
        "$ref": "file:bom-1.4.schema.json#/definitions/vulnerability/properties/analysis"
      }
    }
  }
}

=== apache/solr-site/vex-input/CVE-2019-10086.json
{
  "ids": [
    "CVE-2019-10086"
  ],
  "versions": "8.0.0-8.3.0",
  "jars": [
    "commons-beanutils-1.9.3.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "While commons-beanutils was removed in 7.5, it was added back in 8.0 in error and removed again in 8.3. The vulnerable class was not used in any Solr code path. This jar remains a dependency of both Velocity and hadoop-common, but Solr does not use it in our implementations."
  }
}

=== apache/solr-site/vex-input/CVE-2020-13955.json
{
  "ids": [
    "CVE-2020-13955"
  ],
  "versions": "8.1.0- today",
  "jars": [
    "avatica-core-1.13.0.jar",
    "calcite-core-1.18.0.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Solr's SQL adapter does not use the vulnerable class \"HttpUtils\". Calcite only used it to talk to Druid or Splunk."
  }
}

=== apache/solr-site/vex-input/CVE-2021-45105.json
{
  "ids": [
    "CVE-2021-45105",
    "CVE-2021-45046"
  ],
  "versions": "7.4-8.11.1",
  "jars": [
    "log4j-core-2.14.1.jar",
    "log4j-core-2.16.0.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "The MDC data used by Solr are for the collection, shard, replica, core and node names, and a potential trace id, which are all sanitized. Furthermore, Solr's default log configuration doesn't use double-dollar-sign and we don't imagine a user would want to do that."
  }
}

=== apache/solr-site/vex-input/CVE-2018-8088.json
{
  "ids": [
    "CVE-2018-8088"
  ],
  "versions": "4.x-today",
  "jars": [
    "slf4j-api-1.7.24.jar",
    "jcl-over-slf4j-1.7.24.jar",
    "jul-to-slf4j-1.7.24.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "The reported CVE impacts org.slf4j.ext.EventData, which is not used in Solr."
  }
}

=== apache/solr-site/vex-input/CVE-2017-14868.json
{
  "ids": [
    "CVE-2017-14868",
    "CVE-2017-14949"
  ],
  "versions": "5.2.0-today",
  "jars": [
    "org.restlet-2.3.0.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Solr should not be exposed outside a firewall where bad actors can send HTTP requests. These two CVEs specifically involve classes (SimpleXMLProvider and XmlRepresentation, respectively) that Solr does not use in any code path."
  }
}

=== apache/solr-site/vex-input/CVE-tika-core.json
{
  "ids": [
    "CVE-"
  ],
  "versions": "7.3.1-today",
  "jars": [
    "tika-core.*.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "All Tika issues that could be Solr vulnerabilities would only be exploitable if untrusted files are indexed with SolrCell. This is not recommended in production systems, so Solr does not consider these valid CVEs for Solr."
  }
}

=== apache/solr-site/vex-input/CVE-2017-14952.json
{
  "ids": [
    "CVE-2017-14952"
  ],
  "versions": "6.0.0-7.5.0",
  "jars": [
    "icu4j-56.1.jar",
    "icu4j-59.1.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Issue applies only to the C++ release of ICU and not ICU4J, which is what Lucene uses. ICU4J is at v63.2 as of Lucene/Solr 7.6.0"
  }
}

=== apache/solr-site/vex-input/CVE-2019-10241.json
{
  "ids": [
    "CVE-2019-10241",
    "CVE-2019-10247"
  ],
  "versions": "7.7.0-8.2",
  "jars": [
    "jetty-9.4.14"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Solr upgraded to Jetty 9.4.19 for the 8.2 release. Additionally, the path to exploit these vulnerabilities was fixed in 8.1 and 7.7.2. Earlier versions can manually patch their configurations as described in SOLR-13409."
  }
}
