=== apache/solr-site/plugins/vex/schema/vex-input.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "title": "CycloneDX Software Bill of Materials Standard",
  "items": {
    "type": "object",
    "required": [
      "ids",
      "versions",
      "jars",
      "analysis"
    ],
    "additionalProperties": false,
    "properties": {
      "ids": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "jars": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "versions": {
        "type": "string"
      },
      "analysis": {
        "$ref": "file:bom-1.4.schema.json#/definitions/vulnerability/properties/analysis"
      }
    }
  }
}

=== apache/solr-site/vex-input/CVE-2019-16869.json
{
  "ids": [
    "CVE-2019-16869"
  ],
  "versions": "8.2-8.3",
  "jars": [
    "netty-all-4.1.29.Final.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "This is not included in Solr but is a dependency of ZooKeeper 3.5.5. The version was upgraded in ZooKeeper 3.5.6, included with Solr 8.3. The specific classes mentioned in the CVE are not used in Solr (nor in ZooKeeper as far as the Solr community can determine)."
  }
}

=== apache/solr-site/vex-input/CVE-2024-51504.json
{
  "ids": [
    "CVE-2024-51504"
  ],
  "versions": "9.4.0â€“9.8.1",
  "jars": [
    "zookeeper-3.9.0.jar",
    "zookeeper-3.9.1.jar",
    "zookeeper-3.9.2.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "justification": "requires_configuration",
    "detail": "Solr production deployments are unlikely to be affected.\nExploitation requires Solr to run in SolrCloud mode with the embedded (non-production) Zookeeper server.\nIt also requires the Zookeeper Admin Server to be manually enabled in the configuration."
  }
}

=== apache/solr-site/vex-input/CVE-2021-44832.json
{
  "ids": [
    "CVE-2021-44832"
  ],
  "versions": "7.4-8.11.1",
  "jars": [
    "log4j-core-2.14.1.jar",
    "log4j-core-2.16.0.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Solr's default log configuration doesn't use JDBCAppender and we don't imagine a user would want to use it or other obscure appenders."
  }
}

=== apache/solr-site/vex-input/CVE-2022-33980.json
{
  "ids": [
    "CVE-2022-33980"
  ],
  "versions": "< 9.1",
  "jars": [
    "commons-configuration2-2.7.jar"
  ],
  "analysis": {
    "state": "not_affected",
    "detail": "Solr uses commons-configuration2 for \"hadoop-auth\" only (for Kerberos). It is only used for loading Hadoop configuration files that would only ever be provided by trusted administrators, not externally (untrusted)."
  }
}

=== apache/solr-site/vex-input/CVE-2022-39135.json
{
  "ids": [
    "CVE-2022-39135"
  ],
  "versions": "6.5-8.11.2, 9.0",
  "jars": [
    "calcite-1.31.0.jar"
  ],
  "analysis": {
    "state": "exploitable",
    "response": [
      "update"
    ],
    "detail": "Apache Calcite has a vulnerability, CVE-2022-39135, that is exploitable in Apache Solr in SolrCloud mode. If an untrusted user can supply SQL queries to Solr's '/sql' handler (even indirectly via proxies / other apps), then the user could perform an XML External Entity (XXE) attack. This might have been exposed by some deployers of Solr in order for internal analysts to use JDBC based tooling, but would have unlikely been granted to wider audiences."
  }
}
